### ISSUE TITLE
Fix Promise Conventions

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#241]
I noticed that sometimes new developers make use of promises incorrectly. Sometimes even I forget an `await` and there is a dangling asynchronous operation here. I think these problems should be caught automatically by a linting system.

I've found 3 rules that can help in some cases:

* https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md
* https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md
* https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md

We should incorporate these and see if they work for our current codebase and towards the future reduce the incidence rate of these sorts of bugs.

### Tasks

1. [x] - Incorporate all 3 rules
2. [x] - Detect how many errors occur and warnings, identify which rules are too stringent and we can not use them
3. [x] - Fix errors and warnings

**Comment by joshuakarp** [comment]
Also related to #272

**Comment by CMCDragonkai** [comment]
We are not using this one https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md because sometimes we want to return the promise, and sometimes we want to await it. It depends on the situation. And it's just an optimisation problem.

**Comment by CMCDragonkai** [comment]
The other 2 are now applied in https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/213

**Comment by CMCDragonkai** [comment]
Also a little change:

```
    "@typescript-eslint/no-misused-promises": ["error", {
      "checksVoidReturn": false
    }],
```

We do have situations where we are passing an async function to somewhere that expects a sync function but it working just fine, usually for event handling.

**Comment by CMCDragonkai** [comment]
This is done with the merging of https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/213.
