### ISSUE TITLE
Linting Standardisation: Import Sort Order, Member Order, Member Accessibility, Type Imports, Spaced Comment, Usage of fs

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#272]
Incorporate the new import sort order standard from https://github.com/MatrixAI/TypeScript-Demo-Lib/commit/393bc346b8d277b2a7043c752f52b1d8e910a042

This should ensure that our imports are always aligned in the same order.

This should be done after the loose ends are merged from #240 and #259 as they involve some changes that could screw them up. Instead this will affect likely all the files.

### Tasks

1. [x] - Add in the `eslint-plugin-import` NPM dependency
2. [x] - Run the `npm run lintfix`
3. [x] - Do a full test to see if everything still works
4. [x] - Merge

---

All the rules that will be useful here:

* https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md
* https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md
* https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md
* https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-imports.md
* https://eslint.org/docs/rules/spaced-comment
* https://github.com/mysticatea/eslint-plugin-node
* https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-throw-literal.md

**Comment by CMCDragonkai** [comment]
Rule explanation is here: https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md

I've added in the minimal amount of configuration that I think can work.

**Comment by CMCDragonkai** [comment]
Missed one rule for `@` itself, so it should be this instead, already updated on TS Demo Lib:

```json
    "import/order": [
      "error",
      {
        "groups": [
          "type",
          "builtin",
          "external",
          "internal",
          "index",
          "sibling",
          "parent",
          "object"
        ],
        "pathGroups": [
          {
            "pattern": "@",
            "group": "internal"
          },
          {
            "pattern": "@/**",
            "group": "internal"
          }
        ]
      }
    ],
```

**Comment by CMCDragonkai** [comment]
This can now be done. Should squeeze it in quick so that everybody's imports can be in the right order.

**Comment by CMCDragonkai** [comment]
Might as well bundle:

* https://github.com/mysticatea/eslint-plugin-node - for disallowing raw imports for `fs`
* https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md - member order
* https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md - member accessibility

**Comment by joshuakarp** [comment]
Supporting work - can be quickly added and checked once Gitlab MR is merged.

**Comment by CMCDragonkai** [comment]
Also to bundle this: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-imports.md

**Comment by CMCDragonkai** [comment]
Also this:

https://eslint.org/docs/rules/spaced-comment

**Comment by CMCDragonkai** [comment]
Renamed issue to indicate all the linting standardisation we want to use.

**Comment by CMCDragonkai** [comment]
Also discovered this problem: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-throw-literal.md

Forgot to do `new` in our throws.

**Comment by CMCDragonkai** [comment]
For https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/213

1. Import sorting is applied
2. Spaced comment is applied
3. No throw literal also applied
4. Consistent type imports too

**Comment by CMCDragonkai** [comment]
The node plugin is not needed to control imports. In fact we may need to import `fs` legitimately in our `tests` and in some places in `src` until we can create our own `FileSystem` type fully.

**Comment by CMCDragonkai** [comment]
For access modifiers, we can do this when we update the typescript-eslint and use this:

```
    "@typescript-eslint/explicit-member-accessibility": ["error", {
      "accessibility": "explicit",
      "overrides": {
        "parameterProperties": "off"
      }
    }],
```

That will do auto fixing. But we won't add it yet.

**Comment by CMCDragonkai** [comment]
With the merging of https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/213.

All of this is done except: 

* https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md
* https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md

Both cannot be done for now because they are not autofixable until we upgrade our eslint dependencies.

I think this is acceptable for now so we're going to close this issue.
