### ISSUE TITLE
Integrate SonarQube or SonarLinting

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#295]
SonarQube and associated projects provide even higher level linting rules that can help improve team's code quality.

Their list of rules they can apply are here: https://rules.sonarsource.com/typescript

They have a cloud version of their product here: https://sonarcloud.io/welcome. It is free for open source projects.

There seems to be multiple ways of integrating it:

* https://github.com/rx-ts/eslint-plugin-sonar
* https://github.com/SonarSource/eslint-plugin-sonarjs
* https://richhewlett.com/2020/11/04/moving-sonar-rules-closer-to-the-developer-with-eslint/

Need to investigate which way is the best.

It seems Sonar would run as part of the CI/CD, separate cloud service, or integrated into our eslint.

Asked a question about this here: https://github.com/rx-ts/eslint-plugin-sonar/issues/31

### Tasks

1. [ ] - Find out the best way to integrate
2. [ ] - Attempt integration
3. [ ] - Ensure no conflicts with existing eslint issues
4. [ ] - Fix up linting problems!

**Comment by CMCDragonkai** [comment]
Our level of linting seems sufficient now. Especially in relation to promise mis-use. So I think we can proceed without this.
