### ISSUE TITLE
VaultId and the removal of GenericIdTypes

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#337]
### Specification

The `VaultId` is the last holdout of `GeneridIdTypes.ts`, this file and associated types and errors should be removed from PK in this PR thus solving #299.

`VaultId` should be updated to be an Opaque type of Id from js-id. `GenericIdTypes.ts` should be completely removed. There should be 3 types total. `VaultId`, `VaultIdEncoded` and `VaultIdString`. Converting from `VaultId` to `vaultIdEncoded should use the encode/decode functions inside the vaults utils.

### Additional context
- Fixed by #266 
- Relates to #299 

### Tasks
1. [x] Update `VaultId` to be a Opaque type of Id.
2. [x] add encode/decode functions to vaults utils.
3. [x] add `parseVaultId` function for validation in the validation utils.
4. [x] Update usage of `VaultId` to do conversions where needed.  convert to `VaultIdEncoded` when it can be seen by user and GRPC. Use `VaultIdString` where string is needed internally.
5. [x] make sure the user/ network boundary applies proper validation where needed.
6. [x] Remove the `GenericIdTypes.ts` and related tests.
