### ISSUE TITLE
Vaults general fixes and QOL

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#340]
### Specification
This issue relates to general fixes and QOL changes.
Change to selective imports in all relevant domains. And ensure there are no import cycles in the vaults domain.

```
     ┌──────────────────┐
     │                  │
     │                  │
Errors────►Types ──┐    │
  │         │      │    │
  │         │      │    │
  ▼         │      │    │
Utils ◄─────┘      │    │
  │                ▼    │
  └─────────► Classes ◄─┘
```

### Additional context
* Related #266 

### Tasks
1. [x] switch Vaults domain to using selective imports.
2. [x] switch vaults tests to using selective imports.
5. [x] Vaults domain errors need to be reviewed and updated with proper descriptions and sysexit codes.
6. [x] `VaultId` decoding needs to be checked for if `fromMultibase` throws an error. this needs to be fixed.
8. [x] `VaultsLog` GRPC method can use the google timestamp type for the timestamp.

**Comment by tegefaulkes** [comment]
The vaultMap will need to use VaultIdString as the keys.

**Comment by CMCDragonkai** [comment]
It would be similar to: 

```
  protected connections: Map<NodeIdString, ConnectionAndLock> = new Map();
```

So yea vault map (the in-memory one) would use `VaultIdString`.

**Comment by tegefaulkes** [comment]
`decodeVaultId` still throws errors in some circumstances. I've made a comment on the PR related to this at https://github.com/MatrixAI/js-id/pull/14#discussion_r810826471.

**Comment by tegefaulkes** [comment]
`VaultId decoding needs to be checked for if fromMultibase throws an error. this needs to be fixed.` will be fixed after MatrixAi/js-id#15 is merged and the `js-id` version is updated here.
