### ISSUE TITLE
Expanding `connectionInfoGetter` functionality

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#355]
### Specification
We need to expand the functionality of `connectionInfoGet` to obtain the connection directly from the `GRPCServer` in the case where we are connecting directly to the `GRPCServer` instead of via the proxies. 

So if the `GRPCServer` is secured we obtain the connection information from the `GRPCServer`.  This can also be undefined 

```ts
if (grpcServer.secured) {
  const certs = grpcServer.getClientCertificates(session);
  // process the certs
} else {
  const connInfo = revProxy.getConnectionInfoByEgress(host, port);
  // process the connInfo
}
```

The session can possiby be obtained via but this will need to be verified.
```ts
/**
 * Acqure the HTTP2 session for a GRPC connection from the server side
 * This relies on monkey patching the gRPC library internals
 * The `ServerSurfaceCall` is expected to be an instance of `Http2ServerCallStream`
 * It will contain `stream` property, which will contain the `session` property
 */
function getServerSession(
  call: ServerSurfaceCall
): Http2Session {
  // @ts-ignore
  return call.stream.session;
}
```

This may need to be speced out further.

### Additional context
- Expands on #342 
- https://github.com/MatrixAI/js-polykey/issues/342#issuecomment-1049456016
- https://github.com/MatrixAI/js-polykey/issues/342#issuecomment-1049466068
- https://github.com/MatrixAI/js-polykey/issues/342#issuecomment-1053857968

### Tasks
* [ ] expand `connectionInfoGetter`'s functionality to obtain the relevant connection info directly from the `RPCServer` if it is secured.
* [ ] 2. Update tests to test
	* [ ] getting connection info when connection through proxies
	* [ ] getting connection info when connecting securly and directly to `GRPCServer`
	* [ ] getting connection info when connection insecurly directly to `GRPCServer`

**Comment by CMCDragonkai** [comment]
Also suggesting to change to `authenticateTLS`. But if the function ultimately returns `ConnectionInfo` type even by acquiring the information from GRPC server, then the name can remain.

**Comment by CMCDragonkai** [comment]
With the new RPC server structure, this function is no longer relevant.

Instead every RPC handler would be expected to take a record of properties.

These properties can include the connecting stream, the remote peer information, the context (including signal and timer), the IOC container for service locating our singleton instances.

**Comment by tegefaulkes** [comment]
This issue was to add the ability to obtain the connection data from the GRPC connection itself. It was needed if we ever did an agent - agent connection directly without a proxy since this information was obtained from the proxy.

With the new RPC we won't be using a proxy. The connection data will be obtained from the QUIC system in this case. This essentially makes this issue irrelevant now. I think we should just close it.

**Comment by CMCDragonkai** [comment]
Ok as long as the content of https://github.com/MatrixAI/Polykey/issues/355#issuecomment-1375025056 is being addressed in the PR.
