### ISSUE TITLE
Setting a Node involves NodeManager and NodeGraph, where NodeManager handles bucket overflow policy

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#359]
### Specification
Adding a node to a `NodeGraph`'s bucket needs to be updated. There are 3 cases when adding a node that need to be handled
1. If the node already exists in the bucket the last updated need to be updated.
2. If the node is not already in the bucket AND the bucket has room. The node is added into the bucket.
3. If the node is not in the bucket AND the bucket is full. We need to ping the oldest node in the bucket, if the old node does not respond we drop it for the new node, otherwise we drop the new node and update the last updated for the old node.

We need to add a `force` flag for always add the new node for manually adding nodes.

The core of the functionality needs to be moved into the `NodeManager`. since the `NodeGraph` is purely data structure the checking of the nodes before adding them should be handled inside the NodeManager.

As implemented, the `NodeGraph` just stores the nodes within buckets and tracks the number of nodes in the bucket. The more complex logic is handled by the `NodeManager` now. 

### Additional context

- https://github.com/MatrixAI/js-polykey/pull/326#issuecomment-1070138301
- Relates #326 
- Relates #212 
- Relates #322 
- Relates #344 
- Relates #150 
- Relates #226 
- Relates #345 

### Tasks
- [x] 1. Remove bucket limit checking and core adding logic from `NodeGraph` to `NodeManager.addNode` method. `NodeGraph` is purely data-structure anything that requires complex checking or networking needs to be outside it.
- [x] 2. Handle cases when adding a node.
  1. [x] Node already exists.
  2. [x] Node exists, bucket has room.
  3. [x] Node exist, bucket is full.
- [x] 3. Add `force` parameter to force adding a node if bucket is full.
- [x] Update testing.
  - [x] fix any tests broken by logic moving to `NodeManager`
  - [x] add test for the 3 cases when adding nodes.
  - [x] add test for `force` parameter

**Comment by tegefaulkes** [comment]
I'm refactoring the `NodeGraph.setNode` to just add a node to the bucket and increment the counter without checking. It also updates the node's lastUpdated and information without incrementing the counter if the node already exists.

However I can see an argument for having separate methods for adding and updating the node. What do you think @CMCDragonkai ?

**Comment by CMCDragonkai** [comment]
@tegefaulkes if this is a development issue, the tasks should be part of the PR that you're working on.

If it's a procedure, then the tasks are part of the issue.

**Comment by tegefaulkes** [comment]
I just noticed that the `NodeGraph.setNode` uses `getUnixtime` which seems to be to the second resolution. It just messd with the test but isn't a problem in general. Why don't we just use the `date.getTime` and use millisecond resolution?

**Comment by CMCDragonkai** [comment]
This functionality has to take into account the design "authenticating" nodes here: https://github.com/MatrixAI/js-polykey/issues/322#issuecomment-1082760728

**Comment by tegefaulkes** [comment]
I'm considering this one done.
