### ISSUE TITLE
Add diagrams to NAT Traversal tests

### ISSUE THREAD

**Issue by emmacasolin** [MatrixAI/Polykey#388]
### Specification
The NAT traversal tests are complex and rely on many utility functions, making it difficult to know what is happening in these tests. It would be helpful to have diagrams at the top of each test showing the architecture of the namespaces and agents involved in each test.

Diagrams needed:
- DMZ
  - [x] Agent 1 (DMZ) -> Agent 2 (DMZ)
  - [x] Agent 1 (DMZ) -> Seed Node -> Agent 2 (DMZ)
- Endpoint-independent mapping (EIM)
  - [x] Agent 1 (EIM) -> Agent 2 (DMZ)
  - [x] Agent 1 (DMZ) -> Agent 2 (EIM)
  - [x] Agent 1 (EIM) -> Agent 2 (EIM)
  - [x] Agent 1 (EIM) -> Seed Node -> Agent 2 (EIM)
  - [x] Agent 1 (EIM) -> Seed Node -> Agent 2 (EDM)
- Endpoint-dependent mapping (EDM)
  - [x] Agent 1 (EDM) -> Agent 2 (DMZ)
  - [x] Agent 1 (DMZ) -> Agent 2 (EDM)
  - [x] Agent 1 (EDM) -> Seed Node -> Agent 2 (EDM)
  - [x] Agent 1 (EDM) -> Seed Node -> Agent 2 (EIM)

### Additional context
- First suggested here: https://github.com/MatrixAI/js-polykey/pull/381#issuecomment-1154639269

### Tasks
1. Create diagrams for each of the NAT tests using ASCII flow
2. Modify test descriptions where necessary to make them clearer

**Comment by CMCDragonkai** [comment]
This is a `procedure`, not `development`.

**Comment by CMCDragonkai** [comment]
I think you've already done some of this in 856388b65775cf95609f304beb46eab377f35f2b. What more is there to do? You should list out the tasks here.

**Comment by emmacasolin** [comment]
Remaining diagrams are all being added in https://github.com/MatrixAI/Polykey/pull/441

**Comment by CMCDragonkai** [comment]
Awesome, please keep doing the diagrams as you are doing your testnet tests too.
