### ISSUE TITLE
Integration tests for docker image

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#407]
### Specification

This issue is to track the progress of PKG integration tests for the docker image. 

A selection of bin tests need to be updated to support using the docker image as the target for testing. 

The main tests that need to be updated in order are;
1. `bin/agent/start.test.ts`
2. `bin/bootstrap.test.ts`
3. rest of `bin/agent`
4. `bin/polykey.test.ts`

Depending on the decided scope, the rest of the tests that could be updated are listed in MatrixAI/Polykey-CLI#10

Some things specific to docker that need to be checked refereed from https://github.com/MatrixAI/js-polykey/issues/389#issuecomment-1180048178. 

1. Rather than `--network host`, you'll need an IP address and Port mapping, make sure this works on the CI/CD too
2. Rather than `--pid host` you'll need handling of the signals by the PK agent
3. With `--userns host` and `--user "$(id -u)"` this may still be necessary locally, in order to allow the files written to be readable by the test code which is running as part of our local user. But on the CI/CD this both may be the root user. But experiment with this.

### Tasks

- [x] 1. update to use `testIf` to explicitly run the test if testing docker. Right now we implicitly running them by disabling the tests that are not supported for docker. 
- [x] 2. convert the following test...
    - [x] `bin/agent/start.test.ts`
    - [x] `bin/bootstrap.test.ts`
    - [x] rest of `bin/agent`
    - [x] `bin/polykey.test.ts
    - [x] rest of the bin tests 
- [x] 3. update `.env.example` with any changes to the required env vars.
- [ ] 4. ensure CI/CD job is working.

**Comment by tegefaulkes** [comment]
So we're running into the quirks of using DIND to run our container. Currently the problem is how mounting the host FS works. Since we're running the `dockerd` daemon in the DIND service container we don't actually have access to the FS that the docker is running on.

 This means I can't actually specify the temp file directory for the docker to run since we can't actually create it for the container. I'm not sure there is a way for us to share the file system between the main container and the DIND service.

That leaves us with the following options.
1. Skip or modify tests that require accessing files created by the docker container. 
2. Modify the `gitlab-runner` to run it's own `dockerd` daemon instead of using a DIND service.

The simpler solution for now is just only do tests that don't require directly accessing the contents of the agent's directory. This is a pretty big restriction however since the docker image is just running the raw node code we don't need to be as exhaustive in the testing here. We only need a limited amount of tests to act as a sanity check.

**Comment by tegefaulkes** [comment]
Nice comment about the problem Here https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227#note_52029664

a possible solution mentioned here is using 
```yaml
variables:
  SHARED_PATH: /builds/shared/$CI_PROJECT_PATH
```

I'll look into this.

Update: Yep, looks like this works.

**Comment by CMCDragonkai** [comment]
The next comment is also insightful: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227#note_52092575

**Comment by CMCDragonkai** [comment]
And also https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227#note_128388116... seems like there's a few ways.

**Comment by tegefaulkes** [comment]
Sweet, it's working. In the recent test all but 1 of the `tests/bin/agent/start.test.ts` succeeded.

**Comment by tegefaulkes** [comment]
Both the `start.test.ts` and `bootstrap.test.ts` is passing now. From here on I just need to convert tests to use docker and the do some cleaning up.

**Comment by tegefaulkes** [comment]
Converted all of the tests now. Just need to test them.

**Comment by tegefaulkes** [comment]
I'm running into a problem that's making no sense. A lot of tests are just timing out, `tests/bin/identities/allowDisallowPermissions.test.ts:102` for example. The command spawns however it never exits and never outputs anything on `stdout` and `stderr`.

I'm pretty sure that the start tests are still working. I need to do some sanity checks.

**Comment by tegefaulkes** [comment]
The sanity check has revealed that the command running inside the container can't connect to an agent running on host or another container. I'm exploring solutions.

**Comment by CMCDragonkai** [comment]
Is it a matter of mapping the right ports? Since we are using dind, both containers the client and the agent would be running in the dind container, so then ports have mapped to be non-conflicting.

I also remember docker supports a sort of "link" or bridge between docker containers rather than port mapping.

**Comment by tegefaulkes** [comment]
They should share the same default network if I remove `--network host` but after doing that it still doesn't connect. I think I have to specify a IP address if I'm not using the host network. I can explore what the network looks like using `docker network inspect`.

The other problem is that some of the tests need to connect to a agent with mocking running on the test host.

**Comment by CMCDragonkai** [comment]
I said that in the CICD, that `--network host` may not work. Because you're not actually running the containers with respect to the host network. You don't have access to it at all, your job is itself a container. So port mapping may be necessary, or using a docker link/bridge.

**Comment by CMCDragonkai** [comment]
Yea so we need to get rid of any mocking. Integration tests will need to test with minimal mocking... 

It looks like linking is a legacy feature now.

* https://stackoverflow.com/questions/41768157/how-to-link-containers-in-docker

It is recommended to use "user defined networking":

* https://docs.docker.com/network/bridge/
* https://docs.docker.com/engine/reference/commandline/network_create/

Will these work in the CI/CD? Not sure. Have a try.

**Comment by CMCDragonkai** [comment]
Hey see these issues and this link:

* https://docs.gitlab.com/ee/ci/services/
* https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1042#note_582203396

The first link goes to: https://docs.gitlab.com/ee/ci/services/#connecting-services

**Comment by CMCDragonkai** [comment]
Also: https://docs.gitlab.com/runner/executors/docker.html#create-a-network-for-each-job

There's some SAAS questions people asked:

* https://forum.gitlab.com/t/gitlab-ci-shared-runner-and-docker-missing-gateway-in-network/67463
* https://forum.gitlab.com/t/gitlab-ci-docker-in-docker-network-inaccessible/55437

**Comment by tegefaulkes** [comment]
Inspecting the network with and without `--network host` set shows no containers in the network?

<details>
	
```
  console.log
    [
        {
            "Name": "bridge",
            "Id": "64b8db696e685496de21762554890d54da715d9a45ced403f75a55d82032fe9c",
            "Created": "2022-07-21T06:44:27.366845638Z",
            "Scope": "local",
            "Driver": "bridge",
            "EnableIPv6": false,
            "IPAM": {
                "Driver": "default",
                "Options": null,
                "Config": [
                    {
                        "Subnet": "172.18.0.0/16"
                    }
                ]
            },
            "Internal": false,
            "Attachable": false,
            "Ingress": false,
            "ConfigFrom": {
                "Network": ""
            },
            "ConfigOnly": false,
            "Containers": {},
            "Options": {
                "com.docker.network.bridge.default_bridge": "true",
                "com.docker.network.bridge.enable_icc": "true",
                "com.docker.network.bridge.enable_ip_masquerade": "true",
                "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
                "com.docker.network.bridge.name": "docker0",
                "com.docker.network.driver.mtu": "1500"
            },
            "Labels": {}
        }
    ]
      at Object.<anonymous> (tests/bin/sanity.test.ts:83:13)
  console.log
    [
        {
            "Name": "host",
            "Id": "d27ec6ed1d4ad75e08bd37a5639a42ae7eb0003fd2d440fa7f1a14247a53465c",
            "Created": "2022-07-21T06:44:27.353684646Z",
            "Scope": "local",
            "Driver": "host",
            "EnableIPv6": false,
            "IPAM": {
                "Driver": "default",
                "Options": null,
                "Config": []
            },
            "Internal": false,
            "Attachable": false,
            "Ingress": false,
            "ConfigFrom": {
                "Network": ""
            },
            "ConfigOnly": false,
            "Containers": {},
            "Options": {},
            "Labels": {}
        }
    ]
      at Object.<anonymous> (tests/bin/sanity.test.ts:84:13)
```
	
</details>

**Comment by tegefaulkes** [comment]
Using `FF_NETWORK_PER_BUILD` seems like a step in the right direction. this will allow the host container to communicate with the service as if they share the network. In this case the DIND should have the host name `docker` and the host should have `build`.

**Comment by tegefaulkes** [comment]
So no luck so far. As a quick test i'm using `agent status` to see if we can connect. I'm using `PK_CLIENT_HOST`, `PK_NODE_ID` and `PK_CLIENT_PORT` to specify what to connect to. Specifying `PK_CLIENT_HOST` as `docker` , `build`, `127.0.0.1`, and `localhost` all fail to connect. I've tried this with and without `--network host`.

While the dind and host share the same network since we're using `FF_NETWORK_PER_BUILD`, we may need some extra config to get the containers in `dind ` to interact with the `dind`'s network. This still doesn't explain why two containers in the `dind` can't see each other. We'll they wouldn't share the same localhost IP. But I can't see their ip's using `network inspect`.

For now I'm exploring some things.
1. Using `--add-host` to connect an ip inside the container to an ip on the `dind`. hopefully we can have all the containers share `127.0.0.1`.
2. See what happens when I connect the containers to a created network,
3. I may have to check some assumptions on how the networks in `dind` and host work within the CI jobs.

**Comment by tegefaulkes** [comment]
I was being dumb again. Turns out the test agent wasn't actually running in docker. I'm re-trying some testing.

**Comment by tegefaulkes** [comment]
They show up in the network now.

<details>

```
    [
        {
            "Name": "bridge",
            "Id": "355444f7f3f26c2310279f695ae32816ef1eeafe2d7e6f01d272bdd916245f8c",
            "Created": "2022-07-22T04:08:27.620395059Z",
            "Scope": "local",
            "Driver": "bridge",
            "EnableIPv6": false,
            "IPAM": {
                "Driver": "default",
                "Options": null,
                "Config": [
                    {
                        "Subnet": "172.17.0.0/16"
                    }
                ]
            },
            "Internal": false,
            "Attachable": false,
            "Ingress": false,
            "ConfigFrom": {
                "Network": ""
            },
            "ConfigOnly": false,
            "Containers": {
                "40cd4cc1b066f0c555e01839310d6c67783fb6050002a81a53784f8739f17a98": {
                    "Name": "charming_bhabha",
                    "EndpointID": "0362d81afff8c7f6ebbb3d82c2c43d2f0091838c07d07959e3646683b851137b",
                    "MacAddress": "02:42:ac:11:00:03",
                    "IPv4Address": "172.17.0.3/16",
                    "IPv6Address": ""
                },
                "a360116583b1fb5652446929f5ae1c955a6fdaddb81672430dfba97b7328affa": {
                    "Name": "funny_brahmagupta",
                    "EndpointID": "f8e2e3e0732e41540f4e2fbe1b054f95ed217bf7c1784e36c96cfb16a08323ef",
                    "MacAddress": "02:42:ac:11:00:02",
                    "IPv4Address": "172.17.0.2/16",
                    "IPv6Address": ""
                }
            },
            "Options": {
                "com.docker.network.bridge.default_bridge": "true",
                "com.docker.network.bridge.enable_icc": "true",
                "com.docker.network.bridge.enable_ip_masquerade": "true",
                "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
                "com.docker.network.bridge.name": "docker0",
                "com.docker.network.driver.mtu": "1500"
            },
            "Labels": {}
        },
        {
            "Name": "host",
            "Id": "1b2dbc325852d2ee47e6b9dceaaf65cea0a50e8d12e0c5cd47ffc056dc562291",
            "Created": "2022-07-22T04:08:27.607721593Z",
            "Scope": "local",
            "Driver": "host",
            "EnableIPv6": false,
            "IPAM": {
                "Driver": "default",
                "Options": null,
                "Config": []
            },
            "Internal": false,
            "Attachable": false,
            "Ingress": false,
            "ConfigFrom": {
                "Network": ""
            },
            "ConfigOnly": false,
            "Containers": {},
            "Options": {},
            "Labels": {}
        },
        {
            "Name": "none",
            "Id": "f6d10ad6cfb163dc5d774cda53498512cf7988c25fde02f9cad1839f2c62e9da",
            "Created": "2022-07-22T04:08:27.597489523Z",
            "Scope": "local",
            "Driver": "null",
            "EnableIPv6": false,
            "IPAM": {
                "Driver": "default",
                "Options": null,
                "Config": []
            },
            "Internal": false,
            "Attachable": false,
            "Ingress": false,
            "ConfigFrom": {
                "Network": ""
            },
            "ConfigOnly": false,
            "Containers": {},
            "Options": {},
            "Labels": {}
        },
        {
            "Name": "testdoc2",
            "Id": "8a83fe5fb0273df93b3cba4e904269b1756cde560cce6cb2377d15bc9ba0d114",
            "Created": "2022-07-22T04:10:06.120853785Z",
            "Scope": "local",
            "Driver": "bridge",
            "EnableIPv6": false,
            "IPAM": {
                "Driver": "default",
                "Options": {},
                "Config": [
                    {
                        "Subnet": "172.19.0.0/16",
                        "Gateway": "172.19.0.1"
                    }
                ]
            },
            "Internal": false,
            "Attachable": false,
            "Ingress": false,
            "ConfigFrom": {
                "Network": ""
            },
            "ConfigOnly": false,
            "Containers": {},
            "Options": {},
            "Labels": {}
        }
    ]
```

</details>

**Comment by tegefaulkes** [comment]
Some success. In the case where the agent and command are both running docker. If we just use the `PK_NODE_PATH` env so the client gets the connection information from the status file then we connect to the agent now.

This is slightly odd since one of the sanity tests are using the same connection information and not connecting. Anyway this solves about half the problem so far.

**Comment by tegefaulkes** [comment]
Oh for the... So `agent status` doesn't attempt to connect if It has the status file. Back to square one.

**Comment by tegefaulkes** [comment]
For now we're going to expedite this issue. This means we're going to focus on enabling tests that would currently work. That is any tests that rely purely on docker and not any mocking or `createPolykeyAgent`. Some tests can be converted to not use `createPolykeyAgent` but that will have to come later.

I will need to create a new issue to specify the remaining changes that need to be done later.

**Comment by CMCDragonkai** [comment]
Make sure all conditional testing utilities that are used should be centralised within the `tests/utils` directory. Try to generalise between the docker integration conditional testing utilities and the ones that were used for the nat testing.

**Comment by CMCDragonkai** [comment]
This centralisation should also be applied to the `pk*` functions. Both the `tests/nat` and `tests/bin` are using them. This should be centralised under `tests/utils` too. You can put under `tests/utils/exec.ts`.

**Comment by tegefaulkes** [comment]
lists of tests that are disabled:
- tests/bin/identities - mocked browser + agent + provider
- tests/bin/keys
	- tests/bin/keys/renew.test.ts - key mocking
	- tests/bin/keys/reset.test.ts - key mocking
- tests/bin/nodes/add.test.ts - mocking ping node
- tests/bin/nodes/claim.test.ts - agent
- tests/bin/nodes/find.test.ts - connected agents
- tests/bin/nodes/ping.test.ts - connected agents
- tests/bin/secrets/secrets.test.ts - agent
- tests/bin/vaults/vaults.test.ts - agent, mocking
- tests/bin/utils.retryAuthentication.test.ts - no spawnng in tests
- tests/bin/utils.test.ts - no spawning

**Comment by tegefaulkes** [comment]
Log of failing tests. Sanity can be ignored. anything under `tests/bin/agent` should be working, might just be timeouts.

<details>

```
Summary of all failing tests
FAIL tests/bin/sanity.test.ts (42.317 s)
  ● sanity › weird problem with normal PK, 127.0.0.1
    thrown: "Exceeded timeout of 20000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
      142 |   //   await testAgent.agentClose();
      143 |   // }, 60000);
    > 144 |   runTestIfPlatforms('docker').each(hosts)(
          |                                           ^
      145 |     'weird problem with normal PK, %s',
      146 |     async (host) => {
      147 |       console.log(`weird problem with normal PK, ${host}`);
      at node_modules/jest-each/build/bind.js:43:11
          at Array.forEach (<anonymous>)
      at tests/bin/sanity.test.ts:144:43
      at Object.<anonymous> (tests/bin/sanity.test.ts:16:1)
  ● sanity › weird problem with normal PK, undefined
    thrown: "Exceeded timeout of 20000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
      142 |   //   await testAgent.agentClose();
      143 |   // }, 60000);
    > 144 |   runTestIfPlatforms('docker').each(hosts)(
          |                                           ^
      145 |     'weird problem with normal PK, %s',
      146 |     async (host) => {
      147 |       console.log(`weird problem with normal PK, ${host}`);
      at node_modules/jest-each/build/bind.js:43:11
          at Array.forEach (<anonymous>)
      at tests/bin/sanity.test.ts:144:43
      at Object.<anonymous> (tests/bin/sanity.test.ts:16:1)
FAIL tests/bin/sessions.test.ts (51.337 s)
  ● sessions › serial commands refresh the session token
    thrown: "Exceeded timeout of 20000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
      47 |     await agentClose();
      48 |   });
    > 49 |   runTestIfPlatforms('linux', 'docker')(
         |                                        ^
      50 |     'serial commands refresh the session token',
      51 |     async () => {
      52 |       const session = await Session.createSession({
      at tests/bin/sessions.test.ts:49:40
      at Object.<anonymous> (tests/bin/sessions.test.ts:22:1)
  ● sessions › unattended commands with invalid authentication should fail
    thrown: "Exceeded timeout of 20000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
      84 |     },
      85 |   );
    > 86 |   runTestIfPlatforms('linux', 'docker')(
         |                                        ^
      87 |     'unattended commands with invalid authentication should fail',
      88 |     async () => {
      89 |       let exitCode, stderr;
      at tests/bin/sessions.test.ts:86:40
      at Object.<anonymous> (tests/bin/sessions.test.ts:22:1)
FAIL tests/bin/agent/lockall.test.ts (40.[544](https://gitlab.com/MatrixAI/open-source/Polykey/-/jobs/2763841406#L544) s)
  ● lockall › lockall ensures reauthentication is required
    thrown: "Exceeded timeout of 20000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
      63 |     },
      64 |   );
    > 65 |   runTestIfPlatforms('linux', 'docker')(
         |                                        ^
      66 |     'lockall ensures reauthentication is required',
      67 |     async () => {
      68 |       const password = agentPassword;
      at tests/bin/agent/lockall.test.ts:65:40
      at Object.<anonymous> (tests/bin/agent/lockall.test.ts:19:1)
FAIL tests/bin/agent/lock.test.ts (30.998 s)
  ● lock › lock ensures re-authentication is required
    thrown: "Exceeded timeout of 20000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
      57 |     },
      58 |   );
    > 59 |   runTestIfPlatforms('linux', 'docker')(
         |                                        ^
      60 |     'lock ensures re-authentication is required',
      61 |     async () => {
      62 |       const password = agentPassword;
      at tests/bin/agent/lock.test.ts:59:40
      at Object.<anonymous> (tests/bin/agent/lock.test.ts:15:1)
```

</details>

**Comment by tegefaulkes** [comment]
Removed `sanity.test.ts` since it's not needed now. the rest of the tests failures was depending on mocking the password prompt. they've been disabled.
