### ISSUE TITLE
Expand `pkStdio`, `pkExec` and `pkSpawn` utils to target executables

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#410]
### Specification

We need to expand the `pkStdio`, `pkExec`, and `pkSpawn` utility commands to support testing executable files such as the win, mac builds and docker container. Counterparts to these commands need to be created. These new commands need to mimic their counterparts but execute the target executable.

### Tasks

1. [x] Create counterpart commands that execute the targeted executable
    * [x] `pkExecTarget`
    * [x] `pkStdioTarget` - this can't work with mocking so keep that in mind.
    * [x] `pkSpawnTarget`
3. [x] add switching utility functions that will use a `pk` command or it's counterpart to execute the command.
4. [x] add code docs to each command clearly specifying usage.

**Comment by tegefaulkes** [comment]
`pkXTarget` commands explicitly take the command now. `global.testCmd` needs to be passed into it. I've also added `pkXSwitch` commands that will switch between the normal and target version of the pk commands. Used like so.
```ts
pkSpawn(args, env, cwd, logger);
// becomes
pkSpawnSwitch(global.testCmd)(args, env, cwd, logger);
```

**Comment by CMCDragonkai** [comment]
And ultimately the `global.testCmd` is specified through an environment variable?

Would it be possible that the test code automatically specifies the `testCmd` depending on the "testing platform", but that it can be overwritten by the env variable **if it is set**.

**Comment by tegefaulkes** [comment]
I think @emmacasolin had a way to check what platform was when tests were running. I'll have to dig through the `NAT` tests for that. Either way we can't do this for the docker tests.

**Comment by CMCDragonkai** [comment]
I think you should keep the entrypoint functions the same name as before. It should be just `pkExec` and `pkSpawn` as before.

But internally switch to a different implementation.

You can do this like:

```ts
function pkExec() {
  if (...) { return pkExecTarget(); }
  // ... original functionality ...
}

function pkExecTarget() {
  // new functionality
}
```
