### ISSUE TITLE
Research & Write Polykey Usecases in Wiki

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#424]
### Tasks

1. [x] - Introduce secrets management
2. [x] - Discuss the 3 situations where secrets management is important: rest, transit, use
3. [x] - Produce usecase involving developer persona, development environment and its applicability to 3 situations
4. [ ] - Produce usecase involving devops/sysadmin on deployment to AWS ECS/Fargate (consider SSM)
5. [ ] - Produce usecase involving company/team on employee onboarding/offboarding
6. [ ] - Produce usecase involving company/team on device provisioning
7. [ ] - Produce usecase involving devops/sysadmin on certificate/key rotation using ACME protocol and letsencrypt
8. [ ] - Produce usecase involving devops/sysadmin and CI/CD involving gitlab
