### ISSUE TITLE
Setup Wiki as a CMS for polykey.io/docs

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#428]
The wiki will be scheduled to go into the polykey.io/docs instead due to https://github.com/github-community/community/discussions/4992. GH wikis are not SEO friendly.

However the wiki is still useful way of editing information compared to editing pages on our website. So a hybrid solution is to have the wiki available but then replicate/mirror the wiki to the website.

How to do this? Well the wiki information is public, and we can use BE server to mirror the information. Because search engines cannot see the wiki anyway, it's fine to have the duplicate information.

However `polykey.io` is hosted by webflow which has their own custom CMS. So how to connect to an external API (possibly serverless) backend to then load custom data. Most important it must do the rendering of HTML itself, and not just a mirror the HTML and present it via SSR, not fetched from JS.

It looks like on webflow, it supports https://university.webflow.com/lesson/href-prefix which allows part of an existing website hosted by your own webserver to reverse proxy a particular url directory to webflow.

However I'm looking to do the opposite, use webflow to reverse proxy a portion of the site to an alternative location. However they only allow this for enterprise: https://webflow.com/feature/reverse-proxy-service-for-enterprise

So it looks like it will be time to to front webflow with our own reverse proxy to serve.

There are 2 options here:

1. Use cloudflare - it is already fronting `polykey.io` and we can use it's page rules and maybe other features to be able to route a subdirectory to a different backend server.
2. Run our own system on AWS, and do the routing there, and upstream to webflow for the CMS and main site... etc. Hopefully the ALB is sufficient for this.

Finally the underlying backend could work as a serverless platfrom like cloudflare workers, and then it just has to fetch the wiki markdown and render the correct page.

This does limit the wiki's formatting to what the HTML is shown. See: https://stackoverflow.com/questions/38480701/can-a-github-wiki-embed-html and https://github.com/bryanbraun/github-wiki-html-test/wiki. Note that even if github wiki itself removes those tags, the code is still in the wiki git, and when we mirror we can render that with custom CSS as well if needed. We will need to incorporate this https://webmasters.stackexchange.com/a/76927

Seems like something to be automated with pulumi when we get to it.

### Tasks

- [ ] 1. Create server backend for fetching wiki source from https://github.com/MatrixAI/Polykey.wiki.git
- [ ] 2. Server backend should be runnable on a "serverless" worker like cloudflare workers
- [ ] 3. Server backend should be caching the git repository, and just fetching changes should be fast, this means filesystem state may need to be cached, either via mounted filesystem, ephemeral storage is fine
- [ ] 4. Server a simple home page from the wiki rendered markdown
- [ ] 5. Try out Cloudflare's page rules in order to route to a server from `polykey.io/docs`
- [ ] 6. Need to integrate the theme appropriately, it's not possible to partially load data from a third party inside webflow template on the backend, only custom code on the frontend, so docs server will need to satisfy the same HTML header and footer of the main website
- [ ] 7. Reuse the polykey.io theme, could be done through a git submodule pointing to website theme code

**Comment by CMCDragonkai** [comment]
So the plan is now:

1. Continue to use webflow as a visual design tool for the main website, it can manage the pages and blog.
2. We create a CI/CD mirrored repository https://gitlab.com/MatrixAI/open-source/Polykey-Docs that mirrors https://github.com/MatrixAI/Polykey.wiki.git, this will provide us the ability to use a SSG to generate static HTML/CSS that can be push-deployed to Cloudflare pages.
3. Have polykey.io/docs point to the new cloudflare pages.

It's important for us to configure the Polykey-Docs repo to prevent force pushes, and to not just pull in diverged changes. This is because there is no branch protection on the wiki for Polykey, and we wouldn't want to allow accidental force pushes.

**Comment by CMCDragonkai** [comment]
The wiki repo will now need a `.gitlab-ci.yaml` file that makes use of 2 tools:

1. wrangler for push deploying to cloudflare - https://developers.cloudflare.com/workers/wrangler/commands/#pages
2. https://docusaurus.io/ as the SSG generator

**Comment by CMCDragonkai** [comment]
I've used gitpod.io to test out docusaurus, it appears to work well. We basically have to configure its docs plugin to use `path: '.'` to point to the root directory because the wiki on github doesn't use `docs` subdirectory that docusaurus is configured by default to use.

There is one point of concern. It appears some aspects of the docs plugin uses markdown "front matter" that is processed by the docs plugin. When adding front matter to the markdown files, it appears to be processed as normal markdown, so it ends up showing up.

I'm not sure to what extend we will need front-matter, or if there is a way to configure it in a different way.

**Comment by CMCDragonkai** [comment]
While playing around with docusaurus, I had this idea that a similar concept can be applied to the project docs that is going to the github pages. It seems we don't need `docs` and instead the CI/CD can build the docs on the fly and push into the `gh-pages` branch. This then allows us not to bother running `npm run docs` manually, and keeps our source repo more clean.

**Comment by CMCDragonkai** [comment]
The cloudflare workers/pages is a really powerful concept, as it seems to the next iteration of microservices, it's much more limited in terms of its runtime capabilities, but at the same time, it's so much faster and easier to develop for. But reducing the "surface complexity", the system becomes alot more streamlined. It becomes little HTTP-driven functions that is then deployed anywhere, with state and logic becoming "cloud-native".

**Comment by CMCDragonkai** [comment]
With the amount of OS packages, it would make sense to eventually lift our nixpkgs overlay to have a public overlay. The private overlay would then overlay on top of the public overlay.

This way we can have a consistent upgrade. But we would need to have an appropriate CI/CD to work with the nixpkgs overlay itself.

**Comment by CMCDragonkai** [comment]
Ok an experiment with subdirectory shows that subpages in subdirectories in the github wiki using gollum shows up as a root level page. So subdirectories aren't really mapped accordingly.

```
testdir/
  testpage.md

Becomes: https://github.com/MatrixAI/Polykey/wiki/testpage
```

Gollum must iterate across all markdown pages. I wonder if this means it will also read in `node_modules`.

This means all of our docs pages in `polykey.io/docs` would have to similarly match gollums more primitive routing structure. Everything is just base-level.

**Comment by CMCDragonkai** [comment]
Ok because `node_modules` will be ignored by `.gitignore` this will be fine.

But this does mean ANY markdown files in the repo will end up being rendered. There doesn't seem to be an exclusion method atm.

**Comment by CMCDragonkai** [comment]
Then the only special pages are:

`Home.md`, `_Footer.md`, and `_Sidebar.md`. The `_Header.md` doesn't exist. And that is the only things special about the GitHub wiki system.

**Comment by CMCDragonkai** [comment]
In the future if we also want to open PRs to the wiki repo: https://sparkbox.com/foundry/github_wiki_tutorial_for_technical_wiki_documentation. That just means a proper github repo for hosting the wiki. It would need to be a 2-way mirror, as that would then provide the ability to push changes to the GitHub wiki repo.

**Comment by CMCDragonkai** [comment]
Atm wrangler2 isn't yet on nixpkgs. https://github.com/NixOS/nixpkgs/issues/176233

There is some minor difference with respect to us, which we only need to publish:

https://developers.cloudflare.com/workers/wrangler/compare-v1-v2/

Likely it will end up as `wrangler2` which should be updated when appropriate.

**Comment by CMCDragonkai** [comment]
The preset classic comes with some additional dependencies:

```
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.2.1",
    "prism-react-renderer": "^1.3.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
```

I took them out for now, because it appears to work fine. But it is necessary for us to develop our own theme.

**Comment by CMCDragonkai** [comment]
Ok so the first build is working along with images.

![image](https://user-images.githubusercontent.com/640797/181065512-5dce38e0-9f86-4ece-bc48-be763a50e4e2.png)

It appears that `README.md` is the default page selected. I'd want to keep `README.md` primarily for documentation contributors, which is why it exists. While `Home.md` should be kept as the primary document at the beginning to standardise between github and the generate docs.

Images was solved by using symlinks in static directory.

**Comment by CMCDragonkai** [comment]
Setting `slug: /` for `Home.md` does end up making `Home.md` the default page. However a warning comes up about duplicate routes. This is not apparently a problem. But if the `README.md` was removed, then the warning goes away. The build still succeeds. Problem is the fact that the slug shows up on github wiki.

**Comment by CMCDragonkai** [comment]
The usage of `slug: /` overrides the `README.md` even the warning exists. It also overrides any usage of `index.md`. The `README.md` ends up not being built at all. I wonder if Github supports anything else other than `Home.md`.

**Comment by CMCDragonkai** [comment]
And without a `Home.md`, github wiki doesn't render a home page, only a contents list: 
![image](https://user-images.githubusercontent.com/640797/181072217-b27535a6-bf7b-42fe-8f35-9019c8436bd1.png)

So it looks like it is needed, and we have to use the `slug: /` for now until a better solution is found, maybe overriding the frontmatter with some other metadata that exists elsewhere.

**Comment by CMCDragonkai** [comment]
Ok the wiki has gone into a new repository https://github.com/MatrixAI/Polykey-Docs which now has a license... and so on. This enables pull requests, and this means we don't have to abide by the github wiki's limited functionality. We can now use docusaurus to its full potential.

Plus it's still easy to edit the wiki by just clicking and editing the wiki on the UI.

**Comment by CMCDragonkai** [comment]
And it also renders the frontmatter properly: https://github.com/MatrixAI/Polykey-Docs/blob/master/Home.md.

**Comment by CMCDragonkai** [comment]
Subsequently in the future we can also move the blog into it, or create it as a separate repository.

**Comment by CMCDragonkai** [comment]
It appears that `docusaurus serve` and `docusaurus start` are somewhat inconsistent in their routing. And plus I don't know what this looks like on cloudflare pages. So next step I need to push up to cloudflare pages and proceed with that to get a sense of how the routing will work on polykey.io/docs.
