### ISSUE TITLE
Standardise Conditional Testing Utilties

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#434]
### Specification

I want to refactor the conditional test utilities to use boolean conditional parameter again, but instead reify the conditions into things like `isWindows`, `isLinux`... etc, then you can combine them up easily with `isWindows || isLinux`... etc. String parameters are not obvious.

Furthermore, it's apparent now that we have situations where a test should run normally, and also under a particular platform, but no other platforms are allowed. And there are tests that we want to run only for a given platform. This behaviour should be standardised.

A standard set of functions should be used:

```
testIf
describeIf
```

The condition should be `testIf(boolean, ...args)` where `...args` is sent to `test`. This makes it easily extendable.

An alternative is `testIf(() => bool, ...args)` where it's a function. A unary function by itself is sort of useless, but it can be useful if we do `testIf((meta: Metadata) => bool, ...args)`, where metadata is actually passed into the predicate which is derived from the usage of the test. However I cannot think of any metadata right now that would be useful. Maybe the test name, test location, `__dirname`... etc.

A predicate can also be asynchronous, which allows it to do runtime side-effects (mostly queries).

However @tegefaulkes says it's annoying to have to write `os.platform() === 'linux'` all the time, so to avoid this, we can "reify" the booleans. This is more obvious and is better for performance as it eliminates a bunch of checks. Basically we can have `isPlatformLinux` and `hasNsenter`... etc. This is already used in `js-logger` under `hasCaptureStackTrace` and `hasStackTraceLimit`. See: https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig and https://www.serendipidata.com/posts/naming-guidelines-for-boolean-variables.

Finally this means that through anyone's interpretation:

```
testIf(isPlatformLinux, ...)
```

Should **only** run if the platform is Linux.

Therefore if we want to run without a platform requirement, then:

```
testIf(isPlatformEmpty || isPlatformLinux, ...args)
```

Which means that you can run under any platform and under platform linux.

Finally for and conditions:

```
testIf(hasNsenter && isPlatformLinux, ...args)
```

Which allows us to wire up conditions.

All of this is lot easier to understand, and isn't that much more to write than what is done already.

### Additional context

* Originally posted https://github.com/MatrixAI/Polykey/pull/411#issuecomment-1197616576

### Tasks

- [x] 1. Move `tests/utils.ts` to `tests/utils/utils.ts` and add `tests/utils/index.ts`.
- [x] 2. create a set of reifyed booleans for common test conditions in test utils.
	- platforms
	- expected shell programs for nat testing
- [x] 3. update all `runTestIf` to use `testIf` with reifyed booleans.
- [x] 4. remove`runTestIfPlatform` and `runDescribeIfPlatform`, replace with reifyed booleans and `testIf`

**Comment by tegefaulkes** [comment]
Test utils will need to be updated with an index.ts and the `tests/utils.ts` should be moved to `test/utils/utils.ts`, Should we add the reifyed conditions to utils.ts or their own separate `conditions.ts`?

**Comment by tegefaulkes** [comment]
`setupGlobalAgent` still exists in the utils but is no longer used since #420. I should remove it.

**Comment by tegefaulkes** [comment]
Shortlist of booleans to support.
- isPlatformLinux
- isPlatformMacOs
- isPlatformWindows
- isPlatformDocker
- isPlatformEmpty
- hasIp
- hasIptables
- hasNsenter
- hasUnshare

So far I think these are the only conditions we are checking. 

For the `isPlatform` booleans, they are going to be set based on the `PK_TEST_PLATFORM` variable and mainly used for platform specific testing. However for the NAT testing we are checking if `process.platform === 'linux'`. What this really means is that we should run the test be default only if we're running in linux and certain shell commands are avaliable. this is not the same as `isPlatformLinux` or `isPlatformEmpty`. I think this needs an extra boolean along the lines of `isUnix` that is checking for `process.platform === 'linux'`. Suggestion for a better name is welcome.

**Comment by CMCDragonkai** [comment]
I don't see why we need `isUnix`. When we want multiple things together, you just need to do `isPlatformLinux && hasIptables`.

Does `PK_TEST_PLATFORM` override doing any kind of `process.platform === 'linux'`, maybe this is not needed anymore?

**Comment by CMCDragonkai** [comment]
Based on #435, the usage of these conditions are intended to be a "disallow list" filtering.

The "allow list" filtering should be changed to using directories as grouping. However it depends on a solution #435's reusable test cases.

Therefore the intention of `testIf` and `describeIf` is to communicate to the user to not run this test if the condition is not true.

**Comment by CMCDragonkai** [comment]
Ok so for now, we can have (change to the actual names that `process.platform()` returns):

```
isPlatformLinux
isPlatformDarwin
isPlatformWin32
isTestPlatformDocker
isTestPlatformEmpty
```

But the `isTestPlatform*` is temporary until #435 becomes possible, after which, there is no more need for `PK_TEST_PLATFORM`, and instead we just directly test a directory like `npm test -- ./tests/integration/docker`.

After which those tests return back to normal `test(...)` but we import them to `tests/integration/docker`.

**Comment by CMCDragonkai** [comment]
You can group this under:

```
platformUtils.isLinux
platformUtils.hasIp
platformUtils.hasIptables
platformUtils.hasNsenter
```
