### ISSUE TITLE
End-to-end dev loop: setup a script to like dev-server that re-runs Polykey agent upon changes to source code

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#469]
When developing web applications we often had a hot-reload system that would recompile code and reload the browser upon any fix or feature to any layer of the stack.

This kept us honest and allowed us to see what was going on in the entire application and reminded us how it works.

However for CLI applications like PK, we haven't been doing this, so we don't see how our features/fixes impact the CLI, especially if something has been breaking. All we have are jest tests that target the specific layer we are working on.

So we need to have an end-to-end loop that re-runs Polykey (not just automated tests in jest) that shows us the final output on the terminal, so we can remember how this actually works from the user's perspective.

Then on the end of each PR feature, we can copy paste the output of all these terminal commands to show if anything usability wise has changed.

### Tasks

- [x] 1. Use `nodemon` and integrate typescript compilation or the usage of `ts-node` to run `pk agent start`. This should be fast now that we are using `swc` and `ts-node` with `swc` doesn't do any caching anyway.
- [x] 2. Allow us to clear the app state to do a full reset of the PK.
- [x] 3. Allow us to run CLI commands repeatedly against the re-run agent repeatedly, but this could also be done by the end-developer.

**Comment by CMCDragonkai** [comment]
Task 2 and 3 is actually something the user can do by sending `--fresh` into it. So for now I'm just doing the simplest possible.

See #470 for implementation.

@tegefaulkes take note.
