### ISSUE TITLE
`RPCClient` specification

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#501]
### Specification

There are 3 parts to the client spec

1.  Creation
2.  Calling Interface
3.  Manifest

#### Creation

The `RPCClient` should be a `CreateDestory` class. It's dependencies should be the logger a generic callback that returns a new stream pair. When used with quic this would be a quic stream. The stream creation callback should take the form of `() => Promise<ReadableWriteablePair<Uint8Array, Uint8Array>`

#### Calling interface

There are the 4 types of calls that can be made. Duplex stream, Client stream, Server stream and unary call. Each of these call types should be supported by a generic caller method. For example the duplex caller can take the form of 

```ts
public duplexCaller<I extends JSONValue, O extends JSONValue>(  
  method: string,  
  metadata: POJO,  
): ReadableWritablePair<O, I>{}
```

Much like the RPCServer, the duplex caller is the generic form that the others are based on. The other 3 callers will wrap the duplex caller. The other 3 types are..

```ts
public serverStreamCaller<I extends JSONValue, O extends JSONValue>(
 method: string,
 params: I
 metadata: string,
): Promise<ReadableStream<O>> {}

public clientStreamCaller<I extends JSONValue, O extends JSONValue>(
 method: string,
 metadata: string,
): Promise<{output: Promise<O>, writable: WriteableStream<I>> {}

public unaryCaller<I extends JSONValue, O extends JSONValue>(
 method: string,
 params: I,
 metadata: string,
): O {}

```

Making a rpc call this way can be done like the following. Ideally the typing would be enforced by a method unique to that call but that needs to be enforced by some manifest some how.

```ts
const result = await rpcClient.unaryCaller<I, O>('someMethod', [1, 2, 3], {});

// Ideally the call will be made like so with all the types enforced.
const result = await rpcClient.someMethod([1,2,3], {});
```

When a generic caller method is called it needs to create a Quic stream and hook itself up to that. This should be done by calling the stream creation callback provided during the RPCClient construction.

There will be two forms of the of the caller interfaces. A more generic RWP form that provides a `ReadableWritablePair` as the interface that is returned when called. The other form will be a co-routine style that mirrors how the handlers are set up. The Co-routine style of `CO` for short can be implemented as the following. 

```ts
type WithDuplexCaller<O, I> = (output: AsyncGenerator<O>) => AsyncGenerator<I>  
function withDuplexCaller<O, I>(method: string, caller: WithDuplexCaller<O, I>, metadata: POJO): Promise<void>  {
 // ...
}
  
await withDuplexCaller<number, number>('method', async function * (output) {  
  for await (const value of output) yield value;  
}, {})
```

This style can be applied to the `DuplexStream`,`ClientStream` and `ServerStream` methods. The unary only makes sense as a simple async function call.

The client stream version would have to provide the output as a promise since in this style we expect to receive the output before inputting data. Alternatively the output can be returned by the function and we only input within it. 

#### Manifest

To avoid boilerplate and enforce typing we need some kind of manifest that will dictate the available methods and their types. 

My first thought was to extend the `RPCClient` and add in the specific caller implementations that way. But that will have too much boilerplate where we create the specific caller methods by wrapping the generic ones. 

If we could provide the manifest in the form of a object type that would be ideal.

```ts
Type Manifest = {
	myUnaryCall: UnaryCaller<number, Array<string>>;
	myDuplexCall: DuplexCaller<{a: string, b: number}, number>;
	...
}
```

This way we could construct the RPCClient as `RPCCllient.createRPCClient<Manifest>()` and have all our caller methods available. This would be a very advanced way of enforcing the types and plenty of prototyping needs to be done on this.

If the manifest can be shared between the client and server then that would be the best outcome.

### Additional context

* Related #249 
* Related #498 

### Tasks

* [x] 1. Class life cycle and construction 
* [x] 2. Generic calling WRP interface
* [X] 3. Generic calling CO style interface
* [x] 4. Specific caller interface support with manifest.
* [x] 6. Raw callers, counterpart to the server's raw handlers.

**Comment by tegefaulkes** [comment]
ETAs
1. Creation: trivial
2. generic callers, 1 day includes tests
3. Specific typing and manifests is a bit tricky to estimate. Still need to work out if a good solution is even possible. I think  a few days for this one.

**Comment by CMCDragonkai** [comment]
The creation of RPC Client will need to take a factory function that creates the stream.

Each method call is going to need a stream to work on.

Can you spec the creation to include the factory function and what it is called.

```
RPCClient.createRPCClient({
  streamFactory: () => Promise<ReadableWritablePair>;
});
```

**Comment by CMCDragonkai** [comment]
The `RPCClient` also needs middleware the same as `RPCServer`.

Ideally the middleware can be written similarly, since both sides will just operate on the streams transparently.

**Comment by tegefaulkes** [comment]
I think I'll make a 3rd spec for how the middle-ware works since it's tightly similar and shared between the client and server side.

Even with the simplified version of it, there are edge cases to be worked out.

**Comment by tegefaulkes** [comment]
#### Expansion to the caller interfaces.

On review the interface as currently designed is essentially a readable writable pair of the streams. So low level callers can just provide the stream's readers and writers to be used.

There are also alternate higher level versions of the callers that can be provided. They will use the same style of the context `withF` or `withG` methods and function similarly to the handlers. We can refer to this style as the Co-routine style or just COs.

For example, the duplex caller can be implemented as 

```ts
type WithDuplexCaller<O, I> = (output: AsyncGenerator<O>) => AsyncGenerator<I>  
function withDuplexCaller<O, I>(method: string, caller: WithDuplexCaller<O, I>, metadata: POJO): Promise<void>  {
 // ...
}
  
await withDuplexCaller<number, number>('method', async function * (output) {  
  for await (const value of output) yield value;  
}, {})
```

There may be one small issue with this style. It expects an output before the call completes. so it doen't make sense for unary output of the unary caller or client stream caller. The unary caller doesn't make sense at all for this style. The client caller would either be given a Promise that resolves with the output. Or the caller method itself returns the output when done but that forces us to finish writing before expecting a return.

**Comment by tegefaulkes** [comment]
#### Changes to the RWP style callers.

Since the low level callers are essentially a RWP we can remove the wrapping generators and just provide the reader and writer interfaces.  Essentially the callerInterface becomes...

```ts
{
  reader: output.getReader(),
  writer: input.getWriter(),
}
```

This simplifies the internals a fair bit. We do need to add two new transformations streams to handle some of the logic that was inside the generators. One for converting error messages to actual errors. Another for converting the inputs to request messages.

**Comment by tegefaulkes** [comment]
3 things left here, 
1. strict typing with the manifest and container types.
2. Client side error handling
3. raw callers.

**Comment by tegefaulkes** [comment]
Ok, so I can easily convert from the handler types to the caller types using a combination of conditional types and map types. So I can enforce the expected types using a record of handler types as a manifest. 

I'm looking at using the proxy now to map the typed 'arbitrary' calls into the underlying generic caller methods. The only problem is... There are 4 kinds of callers and there isn't a good way to map the types to the expected caller.

If the manifest contained one kind of caller then it would be easy. the proxy would only have to map to 1 generic caller. So I could do this with 4 separate manifests for each caller type.

The Core of the problem is that I can't convert the statically defined types to a runtime check and the type is the only distinction between what callers are needed. So going down the proxy route, I'd have to keep each kind of caller separate OR pattern match in the parameters by including a string literal parameter to match on. So calls would end up looking like `duplex('duplex', params)`... It's not ideal.

However my previous idea still works. Making the class generic and forcing the implementation of the callers. It would look something like below. but even with this we'd have to define implementation for both the caller ad withCaller styles.

```ts
const rpcClient = new RPCClient<Manifest>({
  manifest: {
    duplexCaller1: (rpcClient) => {
      const result = rpcClient.duplexStreamCaller('duplexCaller1');
      // Can do any parsing here
      return result;
    }
  }
)
```

It would be easier if there was a way to match on some hidden information. The manifest itself could be a record of `{ type: stringLitteral, handler: SomeHandler}`. This could be provided as the manifest to both the `RPCClient` and `RPCServer`. The key would be the method name, the type use to pattern match for the client and the handler as the implementation for the server and inferring the types for the client.

I think this last idea is workable.

**Comment by CMCDragonkai** [comment]
So just so I understand the problem.

The calls on the server side are identified by the handler name. These handlers take just JSON Message. Or in the case of raw handlers just a bytestream.

This means the only types that are relevant are the input and output types.

When you map the server-side type to the client side stub, you get the appropriate type information.

Now on the client side, the issue is that you have 4 different kinds of callers. And type information doesn't have a runtime element check on.

There's a couple ways to solve this.

One is to have RTTI, a way of having type information available at runtime.

Another is that you actually perform a generic call at the proxy level. I mean for duplex, unary, client streaming and server streaming, there is a generic call variant of all 4 that just pumps info and pumps out info. An async generator basically.

I think the problem here is that you want the client side to have specialised behaviour depending on the type of the call?

Can you give some examples of what client calls would look like for the 4 cases?

Something like:

```
client.methods.unary()
client.methods.clientStreaming()
client.methods.serverStreaming()
client.methods.duplex()
```

What are the input types and what are the output types? I suspect that it would either being taking a callback or returning an async generator.

**Comment by CMCDragonkai** [comment]
I'm still a bit confused on what the client methods will look like. We should do a meeting to go through all the possible variants on Wednesday.

**Comment by tegefaulkes** [comment]
Currently the caller types look like this. The generic types are the same but include a `method:string` parameter.


```ts
type DuplexStreamCaller<I extends JSONValue, O extends JSONValue> =
  () => Promise<ReadableWritablePair<O, I>>

type ServerStreamCaller<I extends JSONValue, O extends JSONValue> =
  (parameters: I) => Promise<ReadableStream<O>>

type ClientStreamCaller<I extends JSONValue, O extends JSONValue> =
  () => Promise<{
    output: Promise<O>,
    writable: WritableStream<I>,
  }>

type UnaryCaller<I extends JSONValue, O extends JSONValue> =
  (parameters: I) => Promise<O>

type RawStreamCaller =
  (params: JSONValue) => Promise<ReadableWritablePair<Uint8Array, Uint8Array>>;
```

The with style callers look like this

```ts
type WithDuplexStreamCaller<I extends JSONValue, O extends JSONValue> =
  (f: (output: AsyncGenerator<O>) => AsyncGenerator<I>) => Promise<void>;

type WithServerStreamCaller<I extends JSONValue, O extends JSONValue> =
  (
    parameters: I,
    f: (output: AsyncGenerator<O>) => Promise<void>,
  ) => Promise<void>;

type WithClientStreamCaller<I extends JSONValue, O extends JSONValue> =
  (f: () => AsyncGenerator<I>) => Promise<O>;

type WithRawStreamCaller =(
  params: JSONValue,
  f: (output: AsyncGenerator<Uint8Array>) => AsyncGenerator<Uint8Array>,
) => Promise<void>

```

**Comment by tegefaulkes** [comment]
I have something working that uses the manifest, conditional and mapping types to convert to the caller types from the manifest and a proxy to handle the calls. The manifest has the following type.

```ts
type HandlerType = 'DUPLEX' | 'SERVER' | 'CLIENT' | 'UNARY' | 'RAW';

type ManifestItem<I extends JSONValue, O extends JSONValue> =
  {
    type: 'DUPLEX',
    handler: DuplexStreamHandler<I, O>
  }
  | {
    type: 'SERVER',
    handler: ServerStreamHandler<I, O>
  }
  | {
    type: 'CLIENT',
    handler: ClientStreamHandler<I, O>
  }
  | {
    type: 'UNARY',
    handler: UnaryHandler<I, O>
  }
  | {
  type: 'RAW',
  handler: RawDuplexStreamHandler,
  }

type Manifest = Record<string, ManifestItem<JSONValue, JSONValue>>

```

I'm just finishing this up, writing tests and some cleaning up.

**Comment by tegefaulkes** [comment]
We want to simplify the client manifest since using the caller classes is a bit much. Essentially we only need a tuple of `[HandlerType, JSONValue, JSONValue]`. I thought about this at the time and I didn't see a neat way to specify the type as a value. 

I can easily specify the type as `type DuplexCaller<I extends JSONValue = JSONValue, O extends JSONValue = JSONValue> = ['DUPLEX', I, O]` and we should be able to specify the types from this. But even with the types we still need a value for this.  The simplest way is `const caller = ['DUPLEX', 0, '']`. but it's not clean using the sentinel values for the types we want. Ideally I don't want to specify the values at all, that's why I went with the classes for the callers since it hides all of this in the base class implementation.

I still think `const caller = new DuplexCaller<number, string>()` is cleaner than `['DUPLEX', 0, '']`. If we had to go with the tuple then I could use the basic type constructors such as `String`, `Boolean`, `Number` to extract the types from. It would end up looking like `['DUPLEX', Number, String]  but that means we end up defining the callers in a vastly different way from the handlers and how would we even construct object types this way?

I can use a function to create the value, Such as `duplexCaller<I, O>(): ['DUPLEX', I, O]` but we end up almost exactly mimicking the class style of doing it. 

 I'm not sure what we gain by changing this? I think using the classes allows us to specify types without hassle and cleanly mirrors how types on the handlers are specified.
