### ISSUE TITLE
Update MacOS GitLab CI/CD configuration by 31st May

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#528]
The beta macos machines will be deprecated by 31st May and from then it will be running on the M1 architecture, and will require us to have premium subscription to GitLab again.

See: 

* https://github.com/MatrixAI/js-quic/issues/7#issuecomment-1551451917
* https://gitlab.com/gitlab-com/runner-saas-macos-access-requests/-/issues/233#note_1394334519

Note that if we were to go towards full cross-compilation we may avoid this. But since we have other code like js-db and later that may still use node-gyp we're going to need it anyway.

Do note that M1 and x64 macos is capable of cross compiling architectures. We don't bother with the universal binary cause it's not needed, we are able to publish separate optional packages atm. That way `lipo` is avoided. That does mean though... when distributing PK, we have to distribute an M1 version and a x64 version. The x64 versions are likely to be deprecated in the following years.

### Tasks

- [x] 1. Use `saas-macos-medium-m1` as the tag.
- [x] 2. Use `macos-12-xcode-14` as the image.
- [x] 3. Make sure to update the `systeminformation` to `5.18.5` if it is being used in benchmarking
- [ ] 4. Test that build still works fine on M1

**Comment by CMCDragonkai** [comment]
I've switched over in `js-async-cancellable`. However since we aren't on premium package atm, it's not working. So for now we will just have disable macos jobs while we proceed.

@tegefaulkes beware of this for PK @amydevs 

Just disable the macos jobs for what you're doing atm.

**Comment by CMCDragonkai** [comment]
This is now doable. Everybody must update their repos with this.

**Comment by tegefaulkes** [comment]
Updated for js-quic.

**Comment by CMCDragonkai** [comment]
When updating to the new macos, for the macos jobs to work when benchmarks are used, we need to update to `5.18.5`.

See: https://github.com/MatrixAI/js-db/pull/64#issuecomment-1607397092

So if there are benchmarks and `systeminformation` exists, then we need to add it in.

**Comment by CMCDragonkai** [comment]
I've done this for js-db and released 5.2.0 for now with the latest libraries.

**Comment by CMCDragonkai** [comment]
I'm going to move this issue to Polykey since it's about all libraries.

**Comment by CMCDragonkai** [comment]
https://github.com/MatrixAI/js-db/pull/63 introduces the ability to separate packages into optional packages for js-db. The js-quic is the first one to do it. But the rust toolchain is alot better than the node-gyp toolchain. So it does require some work, however this is not that important atm. So I'm putting it on hold.

**Comment by CMCDragonkai** [comment]
Another thing I forgot. Make sure your `scripts/*.sh` and `scripts/*.ps1` are executable. Use `chmod u+x`. Otherwise it will fail.

**Comment by CMCDragonkai** [comment]
I've done all the libraries except:

1. js-async-monitor - there's some issue with the tests
2. js-contexts - I want to add in the literal timer before continuing
3. TypeScript-Demo-Lib - this one is pending

Otherwise things to verify include:

1. js-quic
2. js-mdns

And of course finally integration into Polykey. It needs to also address the above with all the updated libraries.

Keep in mind there may be some implementation detail changes which could affect the usage. Like EFS's lifecycle management, and the locks supporting `ctx`, and the `DBTransaction.lock` types may not match anymore especially since we don't take a literal number for timeout but it has to be wrapped up in a `ctx` object.

**Comment by CMCDragonkai** [comment]
Ok TypeScript-Demo-Lib is pending other issues. Async monitor is not really important, won't bother solving that.

Will focus on `js-contexts` to finish that up. And then we can track `js-quic` and `js-mdns` and Polykey.

**Comment by CMCDragonkai** [comment]
The `js-contexts` is done with 1.1.0. It will be released in this PR: https://github.com/MatrixAI/js-contexts/pull/3

**Comment by CMCDragonkai** [comment]
Done in `js-mdns` for now. Will need to release this.

Last thing left is this project itself.

Due to issues with TypeScript-Demo-Lib with `pkg`, the same issues will occur here with PK too. So we need to beware of this when packaging @tegefaulkes

**Comment by tegefaulkes** [comment]
Done for `Polykey`.

**Comment by CMCDragonkai** [comment]
Remember to tick off the tasks above.
