### ISSUE TITLE
Update `client` domain structure

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#563]
### Specification

During #552 the `agent` domain was rolled into the `nodes` domain at `src/nodes/agent`. The agent domain was restructured during this time as well.

1. All the handlers were updated to use default exports.
2. All the handlers were updated to use arrow functions.
3. The `ServerManifest` was moved into the `index.ts`.
4. The caller definitions were moved into `nodes/agent/callers`.
5. The caller definitions were split into separate files. (I don't like this change, it means that each caller which can be defined in a single line need to be spread across 60+ files.) I should check with @CMCDragonkai to see if it's required.
6. `clientManifest` was moved into `nodes/agent/callers/index.ts`.
7. `errors.ts`, `types.ts` and `utils.ts` are in `nodes/agent` directory now.

Pretty much try to structure the client domain like `nodes/agent` directory.  If anything is unclear, make a comment here asking about it.

### Additional context

* Related #522
* Related #562 
* Related #560

### Tasks

* [x] 1. All the handlers were updated to use default exports.
* [x] 2. All the handlers were updated to use arrow functions.
* [x] 3. The `ServerManifest` was moved into the `index.ts`.
* [x] 4. The caller definitions were moved into `nodes/agent/callers`.
* [x] 5. The caller definitions were split into separate files. (I don't like this change, it means that each caller which can be defined in a single line need to be spread across 60+ files.) I should check with @CMCDragonkai to see if it's required.
* [x] 6. `clientManifest` was moved into `nodes/agent/callers/index.ts`.
* [x] 7. `errors.ts`, `types.ts` and `utils.ts` are in `nodes/agent` directory now.

**Comment by addievo** [comment]
@tegefaulkes should ClientManifest be in index too along with ServerManifest?

**Comment by addievo** [comment]
@CMCDragonkai whats the go on 

> The caller definitions were split into separate files. (I don't like this change, it means that each caller which can be defined in a single line need to be spread across 60+ files.) I should check with @CMCDragonkai to see if it's required.

**Comment by tegefaulkes** [comment]
One thing I forgot to mention in the spec. The handler names went from `XYZHandler` to `XYZ`.
