### ISSUE TITLE
Change CLI Demo Gif to Polykey V3 Demo

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#631]
The PK V3 Demo is ready and public: https://vimeo.com/884649667.

However embedding on Github apparently prefers uploaded videos limited to 10 MiB in size.

https://stackoverflow.com/questions/4279611/how-to-embed-a-video-into-github-readme-md

### Tasks
- [ ] 1. Create a minified video 720p - 10MiB
- [ ] 2. Embed it, replace the CLI gif
- [ ] 3. Delete the CLI gif

**Comment by CMCDragonkai** [comment]
```
ffmpeg -i ./Polykey\ Demo\ V3.mp4 -filter:v scale="1280:trunc(ow/a/2)*2" -c:a copy output.mp4
```

```
ffmpeg -i ./output.mp4 -vcodec libx265 -crf 28 output2.mp4
```

Combined:

```
ffmpeg -i ./Polykey\ Demo\ V3.mp4 -filter:v scale="1280:trunc(ow/a/2)*2" -vcodec libx265 -crf 28 -c:a copy final_output.mp4
```

**Comment by CMCDragonkai** [comment]
Attempt with the combined command:

https://github.com/MatrixAI/Polykey/assets/640797/2bc1d773-f160-4891-a7e9-fa770d427416

**Comment by CMCDragonkai** [comment]
Attempt with the separate commands - 5 MiB 

https://github.com/MatrixAI/Polykey/assets/640797/cb99e259-14de-4802-bdf6-ada01913ff81

much smaller.

**Comment by CMCDragonkai** [comment]
It appears libx265 isn't widely supported yet. I'll try see if it can be compressed using only x264.

**Comment by CMCDragonkai** [comment]
With libx264 it works on Linux:

```
ffmpeg -i ./Polykey\ Demo\ V3.mp4 -filter:v scale="1280:trunc(ow/a/2)*2" -vcodec libx264 -crf 28 -c:a copy final_output.mp4
```

https://github.com/MatrixAI/Polykey/assets/640797/61a55468-36b7-4646-a748-a0191c4caaee

**Comment by CMCDragonkai** [comment]
Problem is, initial image is the blank image at the beginning of the video, so the thumbnail isn't that great.

**Comment by CMCDragonkai** [comment]
I might need to try and add a preview frame to the beginning, so that it always shows up properly.

**Comment by CMCDragonkai** [comment]
Another attempt with a 5 frame static image:

https://github.com/MatrixAI/Polykey/assets/640797/2cb72a8d-464c-443a-8945-495aa89f131a

**Comment by CMCDragonkai** [comment]
Ok that didn't work, let's try 1 second length.

https://github.com/MatrixAI/Polykey/assets/640797/a538fee7-8df4-4516-80c5-2cbadc532df8

**Comment by CMCDragonkai** [comment]
https://github.com/MatrixAI/Polykey/assets/640797/607025d5-2947-44fe-a042-343a8a4f38f3

Ok I have no idea how to control the video previews.

**Comment by CMCDragonkai** [comment]
I'm giving up on preview for now.

Uploaded version onto README is a 720p resolution. Which is smaller, but fits the 9.6 MiB.

https://github.com/MatrixAI/Polykey/assets/640797/c94eac24-52b1-493a-8889-3048135bcb30

This is now done on Polykey and Polykey-CLI repos.
