### ISSUE TITLE
Write wiki page about secrets management

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/PolyKey#77]
### Tasks

1. [ ] - Introduce secrets management
2. [ ] - Discuss the 3 situations where secrets management is important: rest, transit, use
3. [ ] - Produce usecase involving developer persona, development environment and its applicability to 3 situations
4. [ ] - Produce usecase involving devops/sysadmin on deployment to AWS ECS/Fargate (consider SSM)
5. [ ] - Produce usecase involving company/team on employee onboarding/offboarding
6. [ ] - Produce usecase involving company/team on device provisioning
7. [ ] - Produce usecase involving devops/sysadmin on certificate/key rotation using ACME protocol and letsencrypt

**Comment by CMCDragonkai** [comment]
https://github.com/MatrixAI/js-polykey/wiki/Secrets-Management

@scottmmorris we just reviewed 3. task involving the developer, there are some things that need to be developed for the CLI to support that usecase we wrote down.

@Zachaccino for the 4. task involving sysadmin/devops, I'll need your help to review.

**Comment by CMCDragonkai** [comment]
All of the above usecases are what we do inside Matrix AI already @tegefaulkes @DrFacepalm, so I'll be asking you separately to review different parts of this.
